export const USER_TOPICS = {
  ACCOUNT_CREATED: "account.created",
  ACCOUNT_DELETED: "account.deleted",
  USER_REGISTERED: "user.registered",
};

export const TRANSACTION_TOPICS = {
  TRANSACTION_EVENTS: "transaction.events",
};

export const TRANSACTION_EVENT_TYPES = {
  INITIATED: "INITIATED",
  ACCOUNT_DEBITED: "ACCOUNT_DEBITED",
  ACCOUNT_DEBIT_FAILED: "ACCOUNT_DEBIT_FAILED",
  ACCOUNT_CREDITED: "ACCOUNT_CREDITED",
  ACCOUNT_CREDIT_FAILED: "ACCOUNT_CREDIT_FAILED",
  ACCOUNT_DEBIT_COMPENSATED: "ACCOUNT_DEBIT_COMPENSATED",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
};

export const ERROR_CODES = {
  ACCOUNT_NOT_FOUND: "ET01",
  INSUFFICIENT_BALANCE: "ET02",
  TRANSACTION_FAILED: "ET03",
};
